classDiagram
    class CommandPatternImplementation {
        implement()\n        execute()\n        configure()
    }
    
    
    class Command {
        implement()\n        execute()\n        configure()
    }
    
