#!/bin/bash
# generate-agent-instructions.sh
#
# Single entry point for propagating skills to ALL supported coding agents.
#
# Adding a new skill:
#   1. Drop a .md file into .claude/commands/
#   2. Run: ./scripts/generate-agent-instructions.sh
#   That's it — the skill becomes available in Claude, Copilot, and OpenCode.
#
# What it does per agent:
#   Claude   → copies .claude/commands/*.md to ~/.claude/commands/ (global slash commands)
#   Copilot  → generates .github/copilot-instructions.md (CLAUDE.md + skill catalog)
#   OpenCode → appends "Available Skills" section to CLAUDE.md (idempotent)
#
# Machine-specific paths (home dir, repo path, username) are replaced with
# portable placeholders in all generated output.
#
# Usage:
#   ./scripts/generate-agent-instructions.sh [project_dir] [coding_repo]
#
# Called by:
#   - install.sh         (install time)
#   - agent-common-setup (every launch via `coding --<agent>`)

set -euo pipefail

PROJECT_DIR="${1:-$(pwd)}"
CODING_REPO="${2:-${CODING_REPO:-$(cd "$(dirname "$0")/.." && pwd)}}"

COMMANDS_DIR="$CODING_REPO/.claude/commands"
CLAUDE_MD="$PROJECT_DIR/CLAUDE.md"

# ──────────────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────────────

log() { echo "[agent-instructions] $*" >&2; }

# Replace machine-specific paths with portable placeholders
sanitize_paths() {
    local home_dir="$HOME"
    local username
    username=$(whoami)

    sed \
        -e "s|${CODING_REPO}|\$CODING_REPO|g" \
        -e "s|${home_dir}|~|g" \
        -e "s|/Users/${username}|~|g" \
        -e "s|/home/${username}|~|g"
}

# Extract multi-line description from YAML frontmatter (handles folded scalar >)
extract_description() {
    local file="$1"
    local in_fm=false in_desc=false desc=""

    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            if $in_fm; then break; fi
            in_fm=true
            continue
        fi
        if ! $in_fm; then continue; fi

        if [[ "$line" =~ ^description: ]]; then
            in_desc=true
            local val="${line#description:}"
            val="${val#"${val%%[![:space:]]*}"}"  # trim leading space
            if [[ "$val" != ">" && -n "$val" ]]; then
                desc="$val"
            fi
            continue
        fi

        if $in_desc; then
            if [[ "$line" =~ ^[a-zA-Z_-]+: ]]; then break; fi
            local trimmed="${line#"${line%%[![:space:]]*}"}"
            if [[ -n "$trimmed" ]]; then
                desc="${desc:+$desc }$trimmed"
            fi
        fi
    done < "$file"
    echo "$desc"
}

# Emit a markdown bullet list of all skills
# Usage: emit_skill_list [prefix]
#   prefix="/"  → "- **/playwright-cli** ..."
#   prefix=""   → "- **playwright-cli** ..."
emit_skill_list() {
    local prefix="${1:-}"
    for cmd_file in "$COMMANDS_DIR"/*.md; do
        [[ -f "$cmd_file" ]] || continue
        local name
        name=$(basename "$cmd_file" .md)
        local desc
        desc=$(extract_description "$cmd_file")
        if [[ -z "$desc" ]]; then
            desc=$(grep -v '^#\|^---\|^$' "$cmd_file" | head -1)
        fi
        echo "- **${prefix}${name}** (\`.claude/commands/$name.md\`): $desc"
    done
}

# ──────────────────────────────────────────────────────────────────────────────
# 1. Claude: install slash commands globally
# ──────────────────────────────────────────────────────────────────────────────
install_claude_global() {
    local target="$HOME/.claude/commands"
    mkdir -p "$target"

    [[ -d "$COMMANDS_DIR" ]] || { log "No .claude/commands/ dir — skipping Claude global"; return 0; }

    local count=0
    for cmd_file in "$COMMANDS_DIR"/*.md; do
        [[ -f "$cmd_file" ]] || continue
        cp "$cmd_file" "$target/$(basename "$cmd_file")"
        ((count++))
    done

    log "Claude: installed $count skill(s) → $target"
}

# ──────────────────────────────────────────────────────────────────────────────
# 2. Copilot: generate .github/copilot-instructions.md
# ──────────────────────────────────────────────────────────────────────────────
generate_copilot_instructions() {
    local target_dir="$1"
    local github_dir="$target_dir/.github"
    local output="$github_dir/copilot-instructions.md"

    mkdir -p "$github_dir"

    {
        cat <<'HEADER'
<!-- AUTO-GENERATED by scripts/generate-agent-instructions.sh — do not edit manually -->
# Copilot Instructions

These instructions are generated from the project's CLAUDE.md and available skills
so that GitHub Copilot CLI follows the same conventions as other agents.

Paths shown as `$CODING_REPO` refer to the root of this repository.
Paths shown as `~` refer to the user's home directory.

HEADER

        if [[ -f "$CLAUDE_MD" ]]; then
            echo "## Project Guidelines"
            echo ""
            # Strip the auto-generated skills section (OpenCode marker) before including,
            # since Copilot gets its own skills section below.
            local marker="## Available Skills (Auto-Generated)"
            awk -v marker="$marker" '
                BEGIN { skip=0 }
                $0 == marker { skip=1; next }
                skip && /^## / { skip=0 }
                !skip { print }
            ' "$CLAUDE_MD" | tail -n +2 | sanitize_paths
            echo ""
        fi

        if [[ -d "$COMMANDS_DIR" ]]; then
            echo "## Available Skills"
            echo ""
            echo "The following skills are available. When a task matches a skill's description,"
            echo "read the full skill file and follow its instructions."
            echo ""
            emit_skill_list ""
            echo ""
        fi

    } > "$output"

    log "Copilot: generated $output"
}

# ──────────────────────────────────────────────────────────────────────────────
# 3. OpenCode: append skill catalog to CLAUDE.md
#    (OpenCode reads CLAUDE.md but has no slash command system)
# ──────────────────────────────────────────────────────────────────────────────
ensure_skill_references_in_claude_md() {
    local claude_md="$1"

    [[ -f "$claude_md" ]] || return 0
    [[ -d "$COMMANDS_DIR" ]] || return 0

    local marker="## Available Skills (Auto-Generated)"

    # Remove existing auto-generated section (idempotent)
    if grep -qF -- "$marker" "$claude_md" 2>/dev/null; then
        local temp
        temp=$(mktemp)
        awk -v marker="$marker" '
            BEGIN { skip=0 }
            $0 == marker { skip=1; next }
            skip && /^## / { skip=0 }
            !skip { print }
        ' "$claude_md" > "$temp"
        mv "$temp" "$claude_md"
    fi

    # Trim trailing blank lines so appending doesn't accumulate empties
    local temp2
    temp2=$(mktemp)
    # Use perl to strip trailing newlines (portable across macOS/Linux)
    perl -0777 -pe 's/\n+\z/\n/' "$claude_md" > "$temp2"
    mv "$temp2" "$claude_md"

    # Append fresh skill catalog
    {
        echo ""
        echo "$marker"
        echo ""
        echo "These skills are defined in \`.claude/commands/\` and provide reusable workflows."
        echo "Read the full skill file when a task matches its description."
        echo ""
        emit_skill_list "/"
        echo ""
    } >> "$claude_md"

    log "OpenCode: updated skill references in $claude_md"
}

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────
main() {
    log "Syncing skills to all agents (project=$PROJECT_DIR)"

    # Always do all three — one skill addition, all agents updated
    install_claude_global
    generate_copilot_instructions "$PROJECT_DIR"
    ensure_skill_references_in_claude_md "$CLAUDE_MD"

    log "Done — skills active in Claude, Copilot, and OpenCode"
}

main "$@"
